# Generated by Django 5.1.3 on 2024-11-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_rename_eventoacademico_eventosacademicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosacademicos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Inicio de Semestre'), ('2', 'Fin de Semestre'), ('3', 'Inicio de Inscripción de Asignaturas'), ('4', 'Fin de Inscripción de Asignaturas'), ('5', 'Receso Académico'), ('6', 'Feriado Nacional'), ('7', 'Feriado Regional'), ('8', 'Inicio de Plazos de Solicitudes Administrativas'), ('9', 'Fin de Plazos de Solicitudes Administrativas'), ('10', 'Inicio de Plazos para la Gestión de Beneficios'), ('11', 'Fin de Plazos para la Gestión de Beneficios'), ('12', 'Ceremonia de Titulación o Graduación'), ('13', 'Reunión de Consejo Académico'), ('14', 'Talleres y Charlas'), ('15', 'Día de Orientación para Nuevos Estudiantes'), ('16', 'Eventos Extracurriculares'), ('17', 'Inicio de Clases'), ('18', 'Último Día de Clases'), ('19', 'Día de Puertas Abiertas'), ('20', 'Suspensión de Actividades Completa'), ('21', 'Suspensión de Actividades Parcial')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
