# Generated by Django 5.1.3 on 2024-11-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_eventosacademicos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosacademicos',
            name='confidencial',
            field=models.BooleanField(default=False),
        ),
    ]
