# Generated by Django 5.1.1 on 2024-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('años', models.IntegerField()),
                ('tamaño', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/perritos/')),
            ],
        ),
    ]
