# Generated by Django 5.1.1 on 2024-11-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduplanner', '0002_eventoacademico_delete_perrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacademico',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventoacademico',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
