# Generated by Django 5.1.3 on 2024-11-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduplanner', '0003_alter_eventoacademico_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoAcademico',
        ),
    ]
